name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.bump.outputs.new_version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Get current version
        id: current
        run: |
          if grep -q 'VERSION = ' version.go; then
            VERSION=$(grep 'VERSION = ' version.go | cut -d'"' -f2)
            echo "Found version: $VERSION"
            echo "current_version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "Version constant not found in version.go, using default"
            echo "current_version=0.1.0" >> $GITHUB_OUTPUT
          fi
      
      - name: Bump version
        id: bump
        run: |
          # Parse current version
          current_version=${{ steps.current.outputs.current_version }}
          echo "Current version: $current_version"
          
          # Split version into components
          IFS='.' read -r -a version_parts <<< "$current_version"
          
          # Handle case where version isn't properly parsed
          if [ ${#version_parts[@]} -ne 3 ]; then
            echo "Invalid version format, resetting to 0.1.0"
            major=0
            minor=1
            patch=0
          else
            major=${version_parts[0]}
            minor=${version_parts[1]}
            patch=${version_parts[2]}
          fi
          
          # Increment patch version
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          
          echo "Current version: $current_version"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          
          # Update version in source file
          if [ -f "version.go" ]; then
            sed -i "s/VERSION = \".*\"/VERSION = \"$new_version\"/" version.go
            echo "Updated version.go to version $new_version"
          else
            echo "Warning: version.go not found"
          fi
      
      - name: Commit and push version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Only commit if there are changes
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add version.go
            git commit -m "Bump version to ${{ steps.bump.outputs.new_version }}"
            git push
          fi

  build:
    needs: bump-version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
        exclude:
          - os: windows
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main # Get the latest code with version bump
      
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      
      - name: Build binary
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o contextor-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contextor-${{ matrix.os }}-${{ matrix.arch }}
          path: contextor-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}

  release:
    needs: [bump-version, build]
    runs-on: ubuntu-latest
    # Only create a release if there was actually a version bump
    if: needs.bump-version.outputs.new_version != ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main # Get the latest code with version bump
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.bump-version.outputs.new_version }}
          name: Release v${{ needs.bump-version.outputs.new_version }}
          draft: false
          prerelease: false
          files: contextor-*/*
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ## Contextor v${{ needs.bump-version.outputs.new_version }}
            
            Automated release from GitHub Actions.
            
            ### Binaries
            - Linux (amd64, arm64)
            - macOS (amd64, arm64)
            - Windows (amd64)